### PR TITLE
Feature/test date fed name

### PR DESCRIPTION
**Pull request by MichaelVessia**
#908

### CODE REVIEW

**Comment by sstangl** [comment]
Only if it were capitalized, right? It's looking for the string "APA", which doesn't match "Apa".

**Comment by photon-rain** [comment]
True - comparing the lower case version is probably a better idea though, since having the lowercase fed in the MeetName is not unthinkable.

**Comment by MichaelVessia** [comment]
If I use the regex listed in the issue would these problems be avoided?

**Comment by sstangl** [comment]
I think the current version is OK. I've never seen anyone use the lowercase abbreviation.

**Comment by sstangl** [comment]
No -- the regex would cause the problem @photon-rain was trying to avoid above.

**Comment by sstangl** [comment]
Thanks!

**Pull request merged**
