### PR TITLE
Update lifters.csv

### PR DESCRIPTION
**Pull request by TrystanOakley**
Changed Will Crozier to William to match his other records

### CODE REVIEW

**Comment by TrystanOakley** [comment]
@sstangl I am not sure why the Travis failed. If you let me know why I will try to fix it.

**Comment by sstangl** [comment]
If you scroll through the error report, it says:

> tests/check-social-media-csv lifter-data/social-media.csv

> Lifter does not exist in database: 'Will Crozier'.

So it's just pointing out that if you rename "Will Crozier" to "William Crozier," then his Instagram will no longer be linked. So the build fails. The fix is to also change his name in social-media.csv.

Also, per the documentation at https://github.com/sstangl/openpowerlifting/blob/master/docs/lifter-name-corrections.md, it's necessary to also update lifter-data/name-corrections.dat with the line "William Crozier,Will Crozier".

**Comment by TrystanOakley** [comment]
Oh, I changed his name in the social-media.csv already so no worries. 

Okay I will.

**Comment by TrystanOakley** [comment]
I already changed his name in the social-media.csv so it shouldn't fail once you accept that pull request first @sstangl

**Comment by sstangl** [comment]
Got it, thanks!

**Pull request merged**
