### PR TITLE
Summer Challenge

### PR DESCRIPTION
**Pull request by TrystanOakley**
@sstangl looks like a lot of misspelled names potentially. He also didnt label gender or equipment so. Another great SPF meet in the books.

### CODE REVIEW

**Comment by sstangl** [comment]
Ah... we don't want to drop attempt information if a federation has provided it.

In this case, we need columns `Squat1Kg` through `Squat3Kg`, and same for `Bench1Kg` through `Bench3Kg` and the same for Deadlift.

I think that means that it needs to be re-imported... that sucks, but I can do it!

**Comment by TrystanOakley** [comment]
Crud

**Comment by TrystanOakley** [comment]
Did you already fix this?

**Comment by sstangl** [comment]
Yes, the fixed commit was merged.

**Pull request closed without merging**
