### PR TITLE
Powerlifting at the Rio 2016 Paralympic Games

### PR DESCRIPTION
**Pull request by emp100k**
I think I finally figured out how to add meets just with the online github site, this is for the ParaPL meet (bench only) at the 2016 Rio Paralympics.

### CODE REVIEW

**Comment by photon-rain** [comment]
I've combined all the files into one request - could you add the missed attempts to the entries files?

**Comment by emp100k** [comment]
yeah no problem

**Comment by photon-rain** [comment]
Cool, thanks.

**Comment by emp100k** [comment]
For missed attempts we put a - in front, but for untaken attempts we just leave it blank right?

**Comment by sstangl** [comment]
@emp100k Yes

**Pull request closed without merging**
