### PR TITLE
Fixed OceaniaPF results that were marked as NZPF

### PR DESCRIPTION
**Pull request by photon-rain**

### CODE REVIEW

**Comment by sstangl** [comment]
@photon-rain Oh dear. Could you please resubmit this, just moving a single meet to replace the NZPF meet that got knocked out?

For example, if the NZPF meet was `1602`, and the last meet beginning with `16xx` was `1626`, move `nzpf/1602` -> `oceaniapf/something` and `nzpf/1626` -> `nzpf/1602`.

Since the order is arbitrary, that accomplishes the same thing but with less churn.

**Comment by sstangl** [comment]
Note that this is intended to fix #290.

**Comment by photon-rain** [comment]
There were 6 NZPF meets that got knocked out - the Oceania champs were listed as 6 different meets (Raw, Single-ply & Bench only with Men's and Women's results for each).

**Comment by sstangl** [comment]
Oh, dang. OK!

**Pull request merged**
