### PR TITLE
Update lifters.csv

### PR DESCRIPTION
**Pull request by TrystanOakley**
Changed Gabrielle Tucker's last name to Mamani because she got married

### CODE REVIEW

**Comment by sstangl** [comment]
There's a much better way to make this kind of change.

First, edit `lifter-data/name-corrections.dat`. The format of each line is: `correct name,misspelling one,misspelling two,...`

So in this case, you would add the line `Gabrielle Mamani,Gabrielle Tucker`.

Then run `scripts/standardize-names lifter-data/name-corrections.dat` from the project root, and it will make all these changes for you in a single commit.

**Comment by sstangl** [comment]
Made that change here: https://github.com/sstangl/openpowerlifting/commit/880db3b01f7d53fa970f4a304af1f9daa90d7a85

**Comment by TrystanOakley** [comment]
Oh thank you. I'll write that down and do it that way next time.

**Comment by sstangl** [comment]
I added documentation here: https://github.com/sstangl/openpowerlifting/blob/master/docs/lifter-name-corrections.md

**Comment by TrystanOakley** [comment]
Thank you.

**Pull request merged**
