### PR TITLE
Bar Benders Of The Bay

### PR DESCRIPTION
**Pull request by TrystanOakley**
@sstangl

### CODE REVIEW

**Comment by TrystanOakley** [comment]
Why does this one look different from the others @sstangl ? It looks like someone already did this meet but it was kept in the todo folder and I redid it or something?

**Comment by sstangl** [comment]
Yes, that seems to be the case.

This was an old meet that used to be in spf/, and was entered before spf-archive/ existed.

When you ran `./helper`, it should have complained something like "mkdir: cannot create directory '0415': File exists." This shouldn't happen too often, but it's worth being aware of.

**Comment by TrystanOakley** [comment]
Yeah it did that. Okay

**Comment by sstangl** [comment]
Resolving as a duplicate, but I'll remove the results file in a separate commit. Sorry about that.

**Comment by TrystanOakley** [comment]
No problem. Shit happens

**Pull request closed without merging**
