### PR TITLE
Added WABDL Meet

### PR DESCRIPTION
**Pull request by camdenmariotti**
Added WABDL meet that closes issue #553 . Was not able to run tests locally.

### CODE REVIEW

**Comment by camdenmariotti** [comment]
WABDL is a drug-tested federation.

**Comment by photon-rain** [comment]
Sorry about the state this pull is in right now - will be fixed first thing tomorrow.

**Comment by camdenmariotti** [comment]
No problem. Sorry for all of the trouble.

**Comment by photon-rain** [comment]
@camdenmariotti I've updated this to the current upstream, you're going to have to do use "git pull --force" if you want to use this fork locally.

**Pull request merged**
