### PR TITLE
Check and fix invalid ig usernames #277

### PR DESCRIPTION
**Pull request by emilyytlin**

### CODE REVIEW

**Comment by sstangl** [comment]
Thank you! The `check-instagram-exists` script looks good.

Some of the miscellaneous changes unfortunately break my meet-entering workflow. I think we should fix that before merging this. Another option would be to remove all the changes that aren't related to this bug.

The problem is that I (and other people) need to be able to execute the files in scripts/ and tests/ from any directory, when adding in meet results. To do that, we just symlinked the dependencies -- then the script doesn't need to know from where it was called (because importations will be done relative to the `PWD`.

Therefore we can't use something like `from scripts import foobar`, unless we add the directory containing `scripts` to the `PYTHONPATH`, as you did in the `Makefile`. But, that also doesn't work -- I start up a number of terminals, none of which inherit environment from each other. Additionally, it would be difficult to tell new volunteers to setup environment variables to make this easier, since they already have a hard time.

I'm not sure what the best solution is here. We've gone with symlinks and manual `sys.path.append('../../scripts')`. Each top-level script could also just figure out its file location and do the correct `sys.path.append` without hardcoding location too much.

The path of least resistance, at least for this patchset, is probably removing the parts unrelated to the issue.

**Comment by emilyytlin** [comment]
Symlinks unfortunately do not work on my computer. I will undo these changes.

**Comment by sstangl** [comment]
OK, that's good to know! I guess the `sys.path.append` logic works on your computer, because you used it in the other pull request. We could hardcode the directory relationship between the script location and the `scripts` directory by using `os.path.dirname(os.path.realpath(__file__))`.

**Comment by emilyytlin** [comment]
Updated

**Comment by sstangl** [comment]
Thank you! :-)

**Pull request merged**
