### PR TITLE
EPA 2016 up to SE

### PR DESCRIPTION
**Pull request by JoWhiteley**

### CODE REVIEW

**Comment by photon-rain** [comment]
Hey Jo which meet is 1631 supposed to be? The data doesn't seem to match up with the meet.

**Comment by sstangl** [comment]
@photon-rain It looks like the results for 1631 are here:

http://www.britishpowerliftingsoutheast.co.uk/Results/Open%202016%20Sat.pdf
http://www.britishpowerliftingsoutheast.co.uk/Results/Open%202016%20Sun.pdf

**Comment by JoWhiteley** [comment]
It should be the South East Open.  I'm not taking the results from the individual regional websites.  They are (or should all be) on www.englishpowerlifting.co.uk which is the overall English fed.  Let me check - I did loads today maybe I got distracted

**Comment by photon-rain** [comment]
Ok I was just reading it wrong - the ordering being different threw me off for a minute.

**Comment by photon-rain** [comment]
Does EPA not assign totals for non full-meet lifters or are those DQs?

**Comment by JoWhiteley** [comment]
DQs

**Comment by JoWhiteley** [comment]
Although there's something wrong there.  Those DQs don't make sense.  I will go back to the source tomorrow and figure it out.

**Comment by sstangl** [comment]
It's OK to land things in a state that doesn't make sense and then just file an issue for it to be resolved later. The only real problem is losing track of things.

**Comment by JoWhiteley** [comment]
OK cool.  I will log myself an issue to follow it up.

**Pull request merged**
