### PR TITLE
EPA / East Midlands 2017

### PR DESCRIPTION
**Pull request by JoWhiteley**
This completes East Midlands region for 2017 and brings 2018 up to date.

This also completes EPA for 2017.  Woop!

### CODE REVIEW

**Comment by photon-rain** [comment]
1805 & 1806 don't have failed lifts marked.

**Comment by JoWhiteley** [comment]
Jamie is going to update those 2

**Comment by photon-rain** [comment]
Cool, cheers.

**Comment by JoWhiteley** [comment]
I have amended 1805 and 1806 to include failed attempts.  Also fixed typos and errors in the original results

**Pull request merged**
