### PR TITLE
Rio 2016

### PR DESCRIPTION
**Pull request by emp100k**
Added missed attempts.

### CODE REVIEW

**Comment by emp100k** [comment]
looks like it doesn't like the 4th attempts...  total = best of first 3 attempts but bestbenchkg needs to be the highest bench including 4th...

**Comment by photon-rain** [comment]
BestBenchKg is the same as the total in this case, we really should rename it Bestof3Kg or something like that.

**Comment by emp100k** [comment]
Right but then won't the 4th attempts not show up on the ranking list?

**Comment by photon-rain** [comment]
I think they still show up - @sstangl how does this work?

**Comment by emp100k** [comment]
the only other error I see for this and the meets.csv is requiring the other file to already exist, but doesn't one need to be uploaded first?

**Comment by photon-rain** [comment]
I'll combine them into one pull request - I've just checked and 4th attempts do show up on the site.

**Comment by emp100k** [comment]
So then I just need to change the bestbenchkg column to equal the totalkg column?

**Comment by sstangl** [comment]
@emp100k @photon-rain The site takes the best of the `BestSquatKg` and `Squat4Kg` columns when displaying the column "Squat".

`BestSquatKg` should be renamed to `Best3SquatKg` -- I'll do this soon. It's the best of the attempts that counted toward the `TotalKg`.

**Comment by emp100k** [comment]
So then in this case I should just make the bestbenchkg of those lifters that made 4th attempts be equal to their totalkg right?

**Comment by sstangl** [comment]
If it's bench-only, yeah, `BestBenchKg = TotalKg`.

**Comment by photon-rain** [comment]
You can go down in weight for 4th attempts in Para-PL? That's bizarre.

**Comment by emp100k** [comment]
Yeah i noticed that too, guess the standard 3 attempts are rising bar like in any other powerlifting meets but 4th attempts are totally un-related...

**Pull request merged**
