### PR TITLE
Update lifters.csv

### PR DESCRIPTION
**Pull request by emp100k**
I think all the weights lifted are in pounds? (not weight classes though)  Otherwise there would be multiple massive world record performances in this meet by young teens 15-17.   do all these weights have to de converted to KG or can they be entered as lbs?

### CODE REVIEW

**Comment by emp100k** [comment]
Ok looks like I can't do the columns like that, do you know the best way to fix this meet data without a huge headache?

**Comment by sstangl** [comment]
If you name the columns with "LBS", for example "Bench1LBS", "TotalLBS", etc., you can run the script `script/csv-tokg` over that file and it will convert all the LBS column to Kg columns.

**Comment by sstangl** [comment]
Or I can do it, since that can't be done from the GitHub interface!

**Comment by sstangl** [comment]
Thanks, good catch.

**Comment by emp100k** [comment]
Hey no problem, and thank you with your help fixing it!  :) 

    On Tuesday, July 18, 2017 3:05 PM, Sean Stangl <notifications@github.com> wrote:
 

 Thanks, good catch.—

**Pull request merged**
