### PR TITLE
Proving Ground Classic

### PR DESCRIPTION
**Pull request by TrystanOakley**
@sstangl check the weight classes as I know the SPF has their weird 117 Kg class but couldn't remember if we were suppsoed to keep it at 117 kg or bump it up. Also there is no body weight.

### CODE REVIEW

**Comment by sstangl** [comment]
That meet looks like a pain to enter. Thank you for doing it!

Regarding the weight class, it's your best judgment. Both versions are OK.

**Comment by sstangl** [comment]
Ah, I was wrong -- the test suite likes 117.5. Using 117 gives a warning.

**Comment by TrystanOakley** [comment]
On Fri, Aug 4, 2017 at 12:28 AM Sean Stangl <notifications@github.com>
wrote:

> Ah, I was wrong -- the test suite likes 117.5. Using 117 gives a warning.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sstangl_openpowerlifting_pull_183-23issuecomment-2D320159877&d=DwMCaQ&c=7ypwAowFJ8v-mw8AB-SdSueVQgSDL4HiiSaLK01W8HA&r=QrLkh9Hgm4OFYnkpWoWTFOD9LXMNtJPJfeRAiZl_Igk&m=eYkXqBEIcHXnzUQU2fSWpsMA9-NDsmnUv660vDTwtZU&s=75ZVBNEfZ9ZquRdEDyY6WzqNxF1A_IMCYwpt7cgOIVM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ac52pLibKeFoHUFkNLyydBvLJ2M-2D-2DoTvks5sUqvngaJpZM4OtN5S&d=DwMCaQ&c=7ypwAowFJ8v-mw8AB-SdSueVQgSDL4HiiSaLK01W8HA&r=QrLkh9Hgm4OFYnkpWoWTFOD9LXMNtJPJfeRAiZl_Igk&m=eYkXqBEIcHXnzUQU2fSWpsMA9-NDsmnUv660vDTwtZU&s=sUoM8T0ZcL27453hTm3d0cymRs0U6NDM6O2RADphu88&e=>
> .
>
I can go back and fix it if you already haven't

**Comment by TrystanOakley** [comment]
Did you already fix it?

**Pull request merged**
