### PR TITLE
Update social-media.csv

### PR DESCRIPTION
**Pull request by TrystanOakley**
Added jonathan Rogers instagram. He runs the /r/powerlifting instagram account by the way.

### CODE REVIEW

**Comment by sstangl** [comment]
@TrystanOakley No lifter of that name is in the DB. Does he maybe spell "Jonathan" in a different way?

**Comment by TrystanOakley** [comment]
What do you mean? The link to that Lifter is in the issue report. He spells
it just like that. His name is also already in the name disambiguatuon list
for something.

**Comment by TrystanOakley** [comment]
I copied and pasted that name into the database search bar and it came right up.

**Comment by sstangl** [comment]
> He spells it just like that. His name is also already in the name disambiguatuon list for something.

The name in the disambiguation list is "Jonathan Rodgers," with a "d".

**Comment by TrystanOakley** [comment]
http://www.openpowerlifting.org/lifters.html?q=Jonathan%20Rogers

**Comment by TrystanOakley** [comment]
You are right, his name is spelled with a Ro"d"gers. Just checked the origional message. But there is still a lifter in the database named rogers

**Comment by sstangl** [comment]
Oh, I see what's happening. You spelled it correctly in the commit -- but in the actual database, because of name disambiguation, his name is now "Jonathan Rodgers #1". So it's complaining that there's no one named "Jonathan Rodgers," because all lifters with that name have pound signs as part of their names.

**Pull request merged**
