### PR TITLE
Added VIP Spring Classic 2018, unsure of text file though

### PR DESCRIPTION
**Pull request by xxxdolorxxx**
Added VIP Spring Classic 2018.
I tried following the guide to create the text file. However it seems I am unable to do it.

### CODE REVIEW

**Comment by photon-rain** [comment]
Hi @xxxdolorxxx, this looks good. The tests are failing because they expect results in kg, /scripts/csv-to-kg can convert LB results to kg - if you're not able to run this we can convert them for you 😃.

**Comment by xxxdolorxxx** [comment]
Hey, sorry for my ignorance, lol. Could you convert them please? I'm in over my head with most of this.
Thank you!

**Comment by photon-rain** [comment]
No problem, I'll fix it up and push it to your branch.

**Comment by photon-rain** [comment]
Couple of minor things - added the "SubDivision" to division name and switched date to YYYY-MM-DD. Apart from that looks good.

**Comment by xxxdolorxxx** [comment]
awesome. Thank you for the help!

**Pull request merged**
