### PR TITLE
Update social-media.csv

### PR DESCRIPTION
**Pull request by TrystanOakley**
Added the following lifters in alphabetical order:

Jeremy Thibodeaux
Anatolii Novopismennyl
Yakov Ionin
Mohamed Bouafia

### CODE REVIEW

**Comment by TrystanOakley** [comment]
Ok I guess I have no idea why the check failed.

**Comment by sstangl** [comment]
If you click the red "X" and scroll down, you can see the error message. (You can also run "make check" locally.)

The error is: `Lifter does not exist in database: 'yakov Ionin'.`
(Capitalization error.)

**Comment by TrystanOakley** [comment]
Ohhhh I see. Did you fix the error or would you like me to fix it?

**Comment by sstangl** [comment]
I haven't fixed it. Yes to fixing it!

**Comment by TrystanOakley** [comment]
Will do!

**Comment by TrystanOakley** [comment]
Fixed it.

**Comment by sstangl** [comment]
Thanks :-)

**Pull request merged**
