### PR TITLE
Added NZPF meets

### PR DESCRIPTION
**Pull request by photon-rain**
Added all of the Auckland Powerlifting meets, some of the Canterbury meets & some of the national meets.

### CODE REVIEW

**Comment by sstangl** [comment]
If you execute `make check` locally, you should be able to run the test suite, which should catch the same errors as the TravisCI build.

**Comment by sstangl** [comment]
Don't worry about those errors -- they're easy for me to fix. (Ala https://github.com/sstangl/openpowerlifting/blob/master/docs/lifter-name-corrections.md)

**Comment by sstangl** [comment]
Merged in https://github.com/sstangl/openpowerlifting/commit/de87a5d330753205332e289c9d9f15c89ea6ee53 (I rebased locally, so GitHub doesn't know that this pull request was "merged".)

Some minor errors fixed in subsequent commits.

Thank you very much! Everything looked good, and that's a ton of meets! Basically thanks to your single-handed efforts, we're now not too terrible for the NZPF! I hope the format was OK to work with.

**Comment by sstangl** [comment]
It's worth mentioning that the `URL` file is intended to be a link to the specific meet result page -- that way, when we have a Web scraper, we'll know which URLs were already entered. Not a big problem, though, and easy to fix later.

**Comment by photon-rain** [comment]
Ok, good to know - will link directly to the meets in future commits.

**Comment by sstangl** [comment]
Thank you! This is a ton of meet data, and I really appreciate you taking the time to add it. It looks good.

I made the following changes:
1. Removed `/name_corrections.csv` and integrated some of its data into `/lifter-data/name-corrections.dat`.
2. Removed whitespace changes to some scripts in `tests/`.

This submission contained changesets from a previous submission, which made rebasing a little more difficult than it should have been.

For future pull requests, it may be easier for both you and me for you to blow away your `master` branch, and have it just track the project's main `master`, then create a new branch for each pull request. That way, your history and my history will match.

Thank you again, this is tremendous work!

**Comment by photon-rain** [comment]
Didn't actually mean to commit name_corrections or the script in /tests - was just using them locally to fix some meet data. 

I'll switch back to your master branch - still getting the hang of using git properly.

**Pull request closed without merging**
